// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package referential

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NirReferential struct {
	ReferentialID int64
	Name          string
	Label         string
	ImagePath     pgtype.Text
	Params        []byte
	CompanyID     pgtype.Int4
	UserAuditID   pgtype.Text
}
